### ISSUE TITLE
RHOMEOFlore - erreur 

### ISSUE THREAD

**Issue by Vottana** [PnX-SI/protocoles_suivi#60]
GN 2.12.3
Monitoring 0.6.0

Bonjour tous le monde, 

j'ai essayé d'installer le module RHOMEOFlore mis en partage, je n'ai fait aucune modification dans les fichiers json.
L'application plante et le log me renvoie l'erreur suivante : 

```
[2024-11-20 11:59:47 +0100] [3978742] [ERROR] Exception on /monitorings/util/init_data/RHOMEOFlore [GET]
Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/utils_flask_sqla/response.py", line 19, in _json_resp
    res = fn(*args, **kwargs)
  File "/home/geonatureadmin/gn_module_monitoring/backend/gn_module_monitoring/routes/data_utils.py", line 84, in get_init_data
    for nomenclature in nomenclature_list["values"]:
KeyError: 'values'
```

Est-ce que vous avez une idée de ce que je dois modifier ? Un problème avec le fichier nomenclature peut-être ?
Merci d'avance !

**Comment by camillemonchicourt** [comment]
Oui, en effet, on dirait un soucis de nomenclature.
L'installation de ce sous-module est censé créé des nomenclatures indiqués dans ce fichier : https://github.com/PnX-SI/protocoles_suivi/blob/master/RHOMEOFlore/nomenclature.json
Mais je ne vois pas / sais pas où peut être le soucis.

**Comment by Vottana** [comment]
J'ai résolu mon pb : le fichier observation.json utilise un champ : l'indice de dominance-abondance de Braun-Blanket. Or ce champ n'est pas créé dans le fichier nomenclature, et la nomenclature n'existe pas de base dans GN. Donc il faut soit le rajouter dans le fichier nomenclature, soit créer la nomenclature dans le backoffice de GN.  Je ferme l'issue !

**Comment by camillemonchicourt** [comment]
Ça vaudrait quand même le coup de revoir ça dans les fichiers du sous-module où de l'expliquer dans le Readme à la racine de ce sous-module pour ne pas que d'autres rencontrent le même soucis ?

**Comment by Vottana** [comment]
Bonjour Colas, 
merci pour la modification du protocole sur Github. Je ne savais pas comment le faire, je ne peux pas modifier directement sur la page du protocole et je suis nulle sur Github.
Pour résoudre le pb lors de l'installation du module, j'ai remplacé à la ligne 35 
`"code_nomenclature_type": "BRAUNBLANQABDOM" par "code_nomenclature_type": "BRAUNBARK"` comme tu le dis
car BRAUNBARK existait déjà dans GN et j'ai ajouté directement dans le backoffice de GN les items de cette nomenclature.
Merci pour le suivi.

**Comment by camillemonchicourt** [comment]
Si il y a des nomenclatures de référence présentes dans les standards SINP, mais pas intégrées dans GeoNature, le mieux est de les ajouter à tout le monde dans le sous-module qui gère les nomenclatures standardes et de référence : https://github.com/PnX-SI/Nomenclature-api-module/

PS : La PR #59 a été intégrée.
